FROM resin/%%RESIN_MACHINE_NAME%%-buildpack-deps

RUN apt-get -q update && apt-get install -yq --no-install-recommends \
        ruby ruby-dev bundler \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

#switch on systemd init system in container
ENV INITSYSTEM on

COPY . /usr/src/app
WORKDIR /usr/src/app
RUN script/bootstrap
CMD script/server
